# Generated by Django 2.1.5 on 2019-01-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name_plural': 'Alunos'},
        ),
    ]
